version: '3'
services:
  db:
    container_name: roletronic_db
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
  node:
    container_name: roletronic_app
    depends_on:
      - db
    build: .
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQL_USER_USER
      - DB_PASSWORD=$MYSQL_USER_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQLDB_LOCAL_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - 5555:5555
    volumes:
      - .:/roletronic
    command: npm run start:dev
volumes:
  dbdata:
